### ISSUE TITLE
Blank Screen when accessing one (out of three) clusters

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#4018]
I have 3 clusters on Digital Ocean under various accounts.
I have always been able to connect to them with Lens.
About a week ago, I suddenly couldn't connect to one of the clusters.
I've tried deleting and re-adding the config in kubectl, I've tried deleting and re-adding it to Lens.
I just get a blank screen.  kubectl works fine, it's just Lens that isn't showing anything.
Lens has no trouble with the other clusters.  They are all running the same version.

Here's a screenshot of Lens and the terminal I launched it from when I try to connect to the cluster that Lens is having issues with:

![Screenshot from 2021-10-12 09-42-00](https://user-images.githubusercontent.com/158380/136996871-d8276707-7b6f-487b-9f18-234ec49a1431.png)

- Lens Version: 5.2.5
- OS: Linux (Mint)
- Installation method (e.g. snap or AppImage in Linux): AppImage

```
apiVersion: v1                                                                                                          
clusters:                                                                                                               
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo2-aaronkube                                                                                               
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo2-caitkube                                                                                                
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo3-personalkube                                                                                            
contexts:                                                                                                               
- context:                                                                                                              
    cluster: do-sfo2-aaronkube                                                                                          
    user: do-sfo2-aaronkube-admin                                                                                       
  name: do-sfo2-aaronkube                                                                                               
- context:                                                                                                              
    cluster: do-sfo2-caitkube                                                                                           
    user: do-sfo2-caitkube-admin                                                                                        
  name: do-sfo2-caitkube                                                                                                
- context:                                                                                                              
    cluster: do-sfo3-personalkube                                                                                       
    user: do-sfo3-personalkube-admin                                                                                    
  name: do-sfo3-personalkube                                                                                            
current-context: do-sfo2-aaronkube                                                                                      
kind: Config                                                                                                            
preferences: {}                                                                                                         
users:                                                                                                                  
- name: do-sfo2-aaronkube-admin                                                                                         
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=cait                                                                                                  
      - 28472d7b-cac9-4eb7-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                                                         
- name: do-sfo2-caitkube-admin                                                                                          
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=cait                                                                                                  
      - 016d3b15-5806-4f83-8921-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                                                         
- name: do-sfo2-redactedkube-admin                                                                                        
  user:                                                                                                                 
    token: --redacted--
- name: do-sfo3-personalkube-admin                                                                                      
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=personal                                                                                              
      - 6f766a4d-2e46-4ca9-90c0-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                   
```

This is a screenshot of the developer console in Lens when it can't connect:
![Screenshot from 2021-10-12 09-51-15](https://user-images.githubusercontent.com/158380/136997624-eeef82a4-8dff-4ca3-b1e0-2251199a70c5.png)

**Comment by liuzqt** [comment]
having same issue in MacOS

```
Lens: 5.2.5-latest.20211001.2
Electron: 12.2.1
Chrome: 89.0.4389.128
Node: 14.16.0

```

**Comment by jbeaudoin11** [comment]
Same for me. Installed lens about 2 weeks ago. Worked well for a while and now i just can't use it. Tried to reinstall the app, remove and add the cluster, still not able to do anything with the app.

I'm on Linux, Zorin OS
```
Lens: 5.2.5-latest.20211001.2
Electron: 12.2.1
Chrome: 89.0.4389.128
Node: 14.16.0
```

**Comment by Nokel81** [comment]
If you turn off "Download kubectl binaries matching the Kubernetes cluster version" in preferences does this problem resolve itself?

**Comment by jbeaudoin11** [comment]
@Nokel81 No

**Comment by Nokel81** [comment]
You have to restart lens currently for that option to be picked up. Including the tray icon

**Comment by jbeaudoin11** [comment]
@Nokel81 Yeah, did restart, the problem doesn't look to be a the kubectl level. At least it's not between kubectl and the cluster. Might be between Lens and kubectl :man_shrugging:.

**Comment by darkpixel** [comment]
@Nokel81 Disabled "Download kubectl binaries matching the Kubernetes cluster version" in prefs, quit out of Lens, started it again.  No change.

**Comment by jbeaudoin11** [comment]
Here is more details about the error message `failed to send IPC message "renderer:cluster-id-of-active-view" to view "unknown=7"`

```
Error: Could not call remote method send. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: TypeError: Object has been destroyed
    at Object.b.send (electron/js2c/browser_init.js:161:2484)
    at /opt/Lens/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:454:71
    at IpcMainImpl.<anonymous> (/opt/Lens/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10374)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.emitter.emit (/opt/Lens/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
```

**Comment by Nokel81** [comment]
Yes thanks, that is a unrelated issue, sorry about the noise.

**Comment by Doraemoe** [comment]
I have the same problem. On mac, I need to delete `~/Library/Application Support/Lens/lens-local-storage*` for it to work again.

**Comment by darkpixel** [comment]
Thanks @Doraemoe--that worked for me.  ```~/.config/Lens``` on Linux.

**Comment by liuzqt** [comment]
@Doraemoe  also worked for me, thanks!

**Comment by phivid** [comment]
Not here ...  I needed to delete wider on my macbookpro:  ` rm -rf ~/Library/Application\ Support/Lens/*`

**Comment by Bezz242** [comment]
Hi all,

Having the same problem. @Doraemoe 's fix works for me. BUT IT IS REPETITIVE.

Cannot tell what causes it, but in many cases, I had a VPN (over which I reach out to Kubernetes with Lens) drop out. Reconnecting didn't fix the problem.

Could this be a cause?

Cheers, B.

**Comment by Nokel81** [comment]
Would you mind providing files under `lens-local-storage`? What OS are you on?

**Comment by Bezz242** [comment]
Hi @Nokel81,

I'm on MacOS, Big Sur 11.6.

For now, it's working and I don't have the contents anymore. Will provide them next time the problem occurs.

Cheers, B.

**Comment by Nokel81** [comment]
Okay thanks, the path will be `~/Library/Application Support/lens/lens-local-storage/`, I am also interested in `~/Library/Application Support/lens/lens-cluster-store.json`

**Comment by Bezz242** [comment]
Hi @Nokel81,

I turned the VPN off and on again, but that in itself did not cause the problem. Overnight, the computer fell into stand-by modus and the VPN timed out. Now I have the problem again.
I will send you the files you mentioned. I will use the mail in your profile, as I am not sureif there is any sensitive data in them.

**Comment by Nokel81** [comment]
Thanks for the information, I will investigate. Thanks for the information about when it occurred. I will delete your information once I am done.

**Comment by Nokel81** [comment]
@Bezz242 Thanks for the files but unfortunately they don't seem to have the cause... will continue investigating.

**Comment by liuzqt** [comment]
@Nokel81  FYI this issue also occurs while I was using VPN, usually I left my laptop in stand-by mode over the night, and the next day this issue might happen, after VPN drop and reconnect (not sure it always happen everytime, I can make some observation later), the situation looks similar to what @Bezz242  was having.  

And I'm running MacOS 10.15.6    

I can send some file for your investigation, but is there some private channel I can share file?

**Comment by Nokel81** [comment]
My work email in smalton @ mirantis.com if that works for you

**Comment by liuzqt** [comment]
@Nokel81  sent, thanks

**Comment by damour** [comment]
![image](https://user-images.githubusercontent.com/881794/138605946-71add89c-598f-414f-9c0d-607fa3722b89.png)
The same problem. Works fine after removing /lens-local-storage/ content.

**Comment by endersonmaia** [comment]
> Thanks @Doraemoe--that worked for me. `~/.config/Lens` on Linux.

that worked for me

**Comment by ondrej-simon** [comment]
Deleting entire `/lens-local-storage/` directory and restarting Lens worked for me, as well. Running Ubuntu 21.10 on Dell XPS 9700. Will take this as a temporary fix until a permanent solution is found. At least this is more comfortable than removing and re-adding the cluster.

**Comment by MuhammetDilmac** [comment]
I have same problem on Pardus 2021 with Gnome.

**Comment by rasmus-e** [comment]
Lens 5.2.5 on MacOS 11.4, 2019 Mac Air, 
same problem, nothing rendered for my 2 remote clusters, but local docker-desktop shows

Solution works, renaming/deleting lens-local-storage 
/Users/(me)/Library/Application Support/Lens/ lens-local-storage

**Perhaps troubleshooting info:**
In Dev console / Networks, some fonts from Lens.css were shown as Pending when not rendering.
Now they are downloaded ok, were blocked smh before. 
```
data:font/ttf;base6… | 200 | font | Lens.css | 956 kB | 92 ms
data:font/woff2;bas… | 200 | font | Lens.css | 15.7 kB | 53 ms
data:font/woff2;bas… | 200 | font | Lens.css | 15.9 kB | 53 ms
data:font/woff2;bas… | 200 | font | Lens.css | 15.8 kB | 52 ms
data:font/ttf;base6… | 200 | font | Lens.css | 286 kB | 56 ms
```

Can't say if the font references have changed now, didn't screenshoot, just noted while angerclicking all tabs :-P

**Comment by nissel** [comment]
I'm having the same problem, clearing everything under ~/Library/Application Support/Lens temporarily fixed it, but it came back.

~~Might have some repo steps. I tried to connect to a cluster with an expired auth token, got a bad authentication error page, then fixed my auth token, clicked reconnect then got the blank screen again. Closing and opening the app still gets the blank screen after that.~~

No just started happening again without any error page this time.

**Comment by daniel-meppiel-sonarsource** [comment]
Hi, same issue here on MacOS Big Sur 11.6, also happens on Lens 5.3.0-alpha.

Executing `rm -rf ~/Library/Application\ Support/Lens/*` solved my issue.

**Comment by ahkui** [comment]
![image](https://user-images.githubusercontent.com/14049597/140892347-fa540aff-a9fd-4fb5-aafd-aaf1e86439f1.png)

Same here

MacOS Big Sur 11.2.1 
Lens: 5.2.6-latest.20211104.1

**Comment by FedericoYST** [comment]
Hi, same issue on Windows 10, Lens: 5.2.6-latest.20211104.1.
Where can I find this folder `~/Library/Application\ Support/Lens/*` on Windows?

**Comment by darkpixel** [comment]
@FedericoYST I'm not a Windows guy, but you might try enabling the option to show "hidden files" and then poke around under ```c:\users\<your_user_name>\appdata```.

My guess is it's somewhere under there.

**Comment by Nokel81** [comment]
Could people please try `5.3.0-alpha.11` from one of the following:

- https://api.k8slens.dev/binaries/alpha.dmg
- https://api.k8slens.dev/binaries/alpha-arm64.dmg
- https://api.k8slens.dev/binaries/alpha.exe
- https://api.k8slens.dev/binaries/alpha.x86_64.AppImage
- https://api.k8slens.dev/binaries/alpha.x86_64.snap
- https://api.k8slens.dev/binaries/alpha.amd64.deb
- https://api.k8slens.dev/binaries/alpha.x86_64.rpm

And see if the variety of fixes we have merged resolves this issue for people.

**Comment by larrywax** [comment]
> Could people please try `5.3.0-alpha.11` from one of the following:
> 
> * https://api.k8slens.dev/binaries/alpha.dmg
> * https://api.k8slens.dev/binaries/alpha-arm64.dmg
> * https://api.k8slens.dev/binaries/alpha.exe
> * https://api.k8slens.dev/binaries/alpha.x86_64.AppImage
> * https://api.k8slens.dev/binaries/alpha.x86_64.snap
> * https://api.k8slens.dev/binaries/alpha.amd64.deb
> * https://api.k8slens.dev/binaries/alpha.x86_64.rpm
> 
> And see if the variety of fixes we have merged resolves this issue for people.

It seems to be working now!

**Comment by darkpixel** [comment]
I only ran into the issue once.  I was never able to reproduce it reliably, so I can't say that ```5.3.0-alpha.11``` fixed it or not.

**Comment by hugginsio** [comment]
On launch of `5.3.0-alpha.11`, I still experienced the issue. However, after deleting `/lens-local-storage/*`, I have not been able to reproduce the issue again.

**Comment by Nokel81** [comment]
@damour So you also have the problem that you seem to be missing some data for that pod-logs tab. Which would throw an `UnhandledPromiseRejectionError`. That should be fixed by https://github.com/lensapp/lens/pull/4376

**Comment by DerGut** [comment]
The latest beta seems to solve the issue I had in #4408

**Comment by pablodz** [comment]
same here

**Comment by Nokel81** [comment]
I have found the cause of why this happens. It happens when we set state within a render function, thus causing react never to render anything and go into a hot loop before crashing on OOM.

https://github.com/lensapp/lens/pull/4376 should fix this for some of the cases, but I will need to do a thorough check in all of our components to make sure that we are not doing that anymore

**Comment by Nokel81** [comment]
Closing as this has been fixed in master.

**Comment by pablodz** [comment]
Thanks @Nokel81

**Comment by ramyadmz** [comment]
command + r solved my issue.

**Comment by mahmoudhossam** [comment]
I'm still having this issue, with the following warnings in devtools:

```
[LENS-VIEW]: not initializing view; unknown clusterId="undefined"
__webpack_modules__.1246.BrowserConsole.log @ BrowserConsole.js:41
```

I've already tried clearing the whole `~/Library/Application Support/lens/` folder and unchecking the "Download kubectl binaries matching the Kubernetes cluster version" checkbox in preferences.

Cmd+R does solve the problem temporarily, but it resets my namespace selection and I have to do this every time I start up Lens which is quite annoying.
