### ISSUE TITLE
Enable kube-prometheus-stack integration on kubeadm setup.

### ISSUE THREAD

**Issue by vipinjn24** [kontena/lens#4635]
**What would you like to be added**:
Enable kube-prometheus-stack integration on kubeadm setup.

**Why is this needed**:
The prometheus operator does not properly support kube-prometheus-stack

**Environment you are Lens application on:**
kubeadm

- Kubernetes distribution: kubeadm baremetal
- Desktop OS: Windows 11

**Comment by vipinjn24** [comment]
On cluster metrics it shows.
![image](https://user-images.githubusercontent.com/1639185/148802565-a05d4011-e4e8-49d1-af3e-67a21afbe047.png)

and on pod metrics it only shows memory.
![image](https://user-images.githubusercontent.com/1639185/148802655-45ba9b26-6efc-443e-8d5d-c546f01213a6.png)
![image](https://user-images.githubusercontent.com/1639185/148803913-63156ab7-fef3-4a98-be1b-4646a26c40a4.png)

**Comment by mnencia** [comment]
This issue is due to this PR https://github.com/lensapp/lens/pull/3653 that broke the support in 5.3.0; it has already been fixed in https://github.com/lensapp/lens/pull/4617

The next version will work out of the box with any version of kube-prometheus-stack greater than 30 (that includes https://github.com/prometheus-community/helm-charts/pull/1692). Meanwhile, you could downgrade Lens to 5.2.7 to have the metrics working again.

**Comment by vipinjn24** [comment]
@mnencia I am currently at 5.3.3, which is the next version you are talking about?

**Comment by mnencia** [comment]
The one that is not yet released.

**Comment by vipinjn24** [comment]
@mnencia I have just downloaded the next version 5.3.4 and it is still showing the same metrics.

You can refer to my bare metal cluster setup here in this issue.
https://github.com/prometheus-community/helm-charts/issues/1696

**Comment by aarononeal** [comment]
The Lens installed stack is showing me no metrics.

**Comment by headyj** [comment]
@aarononeal same here, I even try to downgrade to another version which was working before but without any luck. Seems to be related to the last prometheus release

**Comment by vipinjn24** [comment]
@headyj i never had this working, i have even posted the configuration i am using from the start.

**Comment by headyj** [comment]
For me it was working great since the last update. I thought it was Lens but probably related to prometheus itself
