### ISSUE TITLE
Gcloud: exec: python: not found 

### ISSUE THREAD

**Issue by Zarathustra2** [kontena/lens#4741]
**Describe the bug**
I am on the latest lens version from homebrew (5.3.4) and currently when I try to connect to my GKE cluster I get:

```
E0124 22:37:06.401361 32006 proxy_server.go:147] Error while proxying request: error executing access token command "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 127 output= stderr=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 69: readlink: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 83: dirname: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 69: readlink: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 162: exec: python: not found

error executing access token command "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 127 output= stderr=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 69: readlink: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 83: dirname: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 69: readlink: command not found
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: line 162: exec: python: not found
```

I checked that python is in my path, and I can happily run ` /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud config config-helper --format=json` and I see the config in json format on my terminal.

Does anyone have any ideas what is going wrong and what else I should be checking? 

**Environment:**
- Lens Version: 5.3.4
- OS: [e.g. OSX] macOS Monterry
- Installation method (e.g. snap or AppImage in Linux): brew

All the best,
Dario

**Comment by Miles-Garnsey** [comment]
I am experiencing the same issue. I wasn't having this problem until I installed 5.3.4 and Lens is now unusable for me.

Can someone please provide instructions as to how to downgrade? Even just where to track down a previous .dmg file would be helpful, I can't browse historical releases from `https://api.k8slens.dev/binaries/` unfortunately.

Environment:
Lens Version: 5.3.4
OS: [e.g. OSX] macOS Monterry
Installation method (e.g. snap or AppImage in Linux): .dmg file installer

**Comment by narner90** [comment]
Same issue here:

Environment:
Lens Version: 5.3.4
OS: macOS Monterey 12.0.1
Apple M1
Installation method :.dmg file installer

**Comment by Miles-Garnsey** [comment]
I am no longer seeing this issue having upgraded to `Lens: 5.4.0-latest.20220301.1`.

**Comment by Zarathustra2** [comment]
So far works for me as well, I will wait couple more days that it does not come up again and then will close the ticket

**Comment by Zarathustra2** [comment]
Closing this ticket as it seems fixed in latest version, thanks everyone!

**Comment by narner90** [comment]
I am still having this issue on 5.4.1-latest.20220304.1

```
E0304 18:51:24.710725 65951 proxy_server.go:147] Error while proxying request: error executing access token command "/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 127 output= stderr=google-cloud-sdk/bin/gcloud: line 70: readlink: command not found
/google-cloud-sdk/bin/gcloud: line 84: dirname: command not found
/google-cloud-sdk/bin/gcloud: line 70: readlink: command not found
/google-cloud-sdk/bin/gcloud: line 190: exec: python: not found
```

**Comment by xgenvn** [comment]
@narner90 and others who might have the same issues:
- Sometimes due to zsh/shell environment not fully loaded when restarting the system, and Lens runs on startup (MacOS). You need to force quit Lens from System monitor and start again.

**Comment by narner90** [comment]
@xgenvn that fix does not work for me. I still get that error on `5.4.6-latest.20220428.1` after force quitting.

**Comment by stascnb** [comment]
Same issue
```
readlink: command not found
line 192: exec: python: not found
line 84: dirname: command not found
```

and so on `Lens: 5.5.3-latest.20220602.2`

**Comment by Miles-Garnsey** [comment]
This really needs to be re-opened. I encounter this issue now every time a new Lens version is available, which basically makes every upgrade a forced upgrade. 

Considering what's just happened over [here](https://github.com/lensapp/lens/issues/5444), I think the devs should be taking a long hard look at this.

**Comment by stascnb** [comment]
yep totally, its basically unusable now, just randomly disconnects 

Edit: randomly works well also, its very incosistent.

**Comment by KleyLima** [comment]
Same here with version `6.0.2-latest.20220908.1`

**Comment by KleyLima** [comment]
I use fish, my workaround is use the default bash, and when i use the terminal the first thing i do is type `fish` to start a session.
With the default bash Lens can use gcloud binaries properly.
I think it should work with zsh and so on. Hope it helps.
