### ISSUE TITLE
Unable to connect to any cluster

### ISSUE THREAD

**Issue by Mariani88** [kontena/lens#6515]
**Describe the bug**

Hi everyone, I have an error when I try to enter into a cluster with lens. Every worked fine until I updated Mac OS to Ventura. That was the thing it changed. 

**To Reproduce**
just open Lens and try to enter into any cluster.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:  

Lens: 2022.10.311317-latest
Extension API: 6.1.14
Electron: 19.0.17
Chrome: 102.0.5005.167
Node: 16.14.2
© 2022 Mirantis, Inc.

- OS: [e.g. OSX]. MAC OS Ventura
- Installation method (e.g. snap or AppImage in Linux): Lens web 

**Logs:**
```
Starting connection ...

F1103 22:14:30.475899 3315 main.go:82] failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x618aec0, 0x3, 0x0, 0xc00043ee00, 0x1, {0x5885f53, 0x20}, 0xc000100480, 0x0)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
k8s.io/klog/v2.(*loggingT).printDepth(0x618aec0, 0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000595ae0, 0x2, 0x2})
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1c7
k8s.io/klog/v2.(*loggingT).print(...)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:1490
main.main()
/Users/runner/work/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x725

goroutine 39 [syscall]:
os/signal.signal_recv()
/Users/runner/hostedtoolcache/go/1.17.13/x64/src/runtime/sigqueue.go:166 +0x28
os/signal.loop()
/Users/runner/hostedtoolcache/go/1.17.13/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
/Users/runner/hostedtoolcache/go/1.17.13/x64/src/os/signal/signal.go:151 +0x2c

proxy exited with code: 255

Failed to start connection: Error: failed to retrieve port from stream```


Thank you very much!

**Comment by heinko** [comment]
same for me. Cannot connect to my cluster after upgrading to **_2022.10.311317-latest_**

Fixed by updating my config file to `apiVersion: client.authentication.k8s.io/v1beta1` 

thanks to [#6492 ](https://github.com/lensapp/lens/issues/6492#issuecomment-1298335413)

**Comment by Mariani88** [comment]
I fixed it installing the latest version of awscli, which updated my kubeconfig with that annotation by running aws eks ...

**Comment by pnrao1983** [comment]
I am getting below error:
Failed to get /version for clusterId=595218763226d697de919f8ee415665f: Unauthorized
I have Mac up to date
AWS cli is 2.11
Not sure what is wrong.. any body help me please

**Comment by mrr4cc00n** [comment]
I was getting the same error after months of use without any issues with some GCP's clusters, in my case I just ran `gcloud container clusters get-credentials cluster_name --region myregion --project myproject`. For one of the clusters and it asked for my creds after that I was able to log in normally to all clusters. I short most likely the issue is in your kubeconfig file, try to re-authenticate in one of your clusters

**Comment by pnrao1983** [comment]
No luck for me on this issue:
I am still facing the same issue:
ailed to get /version for clusterId=6451149fa3b4252a6058c28d8312a43d: Unauthorized

The operation was aborted.

Failed to get /version for clusterId=6451149fa3b4252a6058c28d8312a43d: Unauthorized

The operation was aborted.

Failed to get /version for clusterId=6451149fa3b4252a6058c28d8312a43d: Unauthorized

The operation was aborted.

Failed to get /version for clusterId=6451149fa3b4252a6058c28d8312a43d: Unauthorized

Failed to get /version for clusterId=6451149fa3b4252a6058c28d8312a43d: Unauthorized

**Comment by ruscon** [comment]
The same issue
Failed to get /version for clusterId=xxx: Unauthorized

latest awscli and lens

**Comment by hugobytebender** [comment]
anybody has found out how to fix the issue?

**Comment by oorobak** [comment]
same problem here, Failed to get /version for clusterId=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: Unauthorized

any ideas?

**Comment by mrr4cc00n** [comment]
I would recommend to remove those clusters from the kube config ctx and re-authenticate (add the cluster again), as you would normally do, that fixed the issue for me in the past (for both GCP and AWS), see example below. Also verify the cluster is being added as expected to the file mentioned above.

> I was getting the same error after months of use without any issues with some GCP's clusters, in my case I just ran `gcloud container clusters get-credentials cluster_name --region myregion --project myproject`. For one of the clusters and it asked for my creds after that I was able to log in normally to all clusters. I short most likely the issue is in your kubeconfig file, try to re-authenticate in one of your clusters

**Comment by oorobak** [comment]
Unfortunatly same result. I have Win11/newest aws cli/newest kubectl. Added access key, secret and region to aws configure (without that I had diffrent authorization error) and also set as env vars. Kubectl config generated.

Kubectl get nodes works fine from console. I can use cluster from command line, but OpenLens return: Failed to get /version for clusterId=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: Unauthorized

If I change something in config file OpenLens return different errors so OpenLens see the config file. Reseting all cache and configs doesn't work. Other teammates use OpenLens and it works for them, so the problem is in some configuration...?

aws-cli/2.15.25
Client Version: v1.29.2
Kustomize Version: v5.0.4
Server Version: v1.29.0-eks

**Comment by DilshanWij** [comment]
I had the same issue and tried everything on the internet but had no luck. However, opening the Lens via the launcher seems to have caused this issue, and I tried to run it from the terminal using `open /Applications/Lens.app/` and it solved my problem.

Using a Mac with Iterm2.

**Comment by oorobak** [comment]
Yes, I have the same thing, but on Win11. I need to set the avs credentials in the terminal env variables key + secret + token and I need to set `aws configure` and repeat key + secret (+ region and output format) and run Openlens from the current terminal. Of course you also need the kubectl configuration file in ~/.kube/config.

Openlens doesn't see the authorisation from the terminal. And if you think about it a little, it seems logic :D how could a desktop application read temporary variables from a terminal? Nvm. Now it works.
