### ISSUE TITLE
launchMinikubeClusterFromCatalog causes hang/crash on exit during integration test

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#7207]
**Describe the bug**
When running an integration test that uses `utils.launchMinikubeClusterFromCatalog`, the Lens application crashes and does not close, causing Jest to hang.

**To Reproduce**
1. Build the application:
    ```
    $ npm ci
    $ npm run build:app
    ```
2. Create the following file in `packages/open-lens/integration/__tests__/minikube.tests.ts`:
    ```typescript
    import type { Page } from "playwright";
    import * as utils from "../helpers/utils";

    describe("minikube tests", () => {
      let window: Page;
      let cleanup: undefined | (() => Promise<void>);

      beforeAll(async () => {
        ({ window, cleanup } = await utils.start());
        await utils.clickWelcomeButton(window);

        // Navigate to catalog
        await window.waitForSelector('div[data-rbd-draggable-id=catalog-entity]');
        await window.click('div[data-rbd-draggable-id=catalog-entity]');

        // Navigate to minikube cluster
        await utils.lauchMinikubeClusterFromCatalog(window);
      }, 10*60*1000);

      afterAll(async () => {
        await cleanup?.();
      }, 10*60*1000);

      it('noops', async () => {
        // do nothing
      }, 10*60*1000)
    });
    ```
3. Execute this specific integration test:
    ```
    $ cd packages/open-lens
    $ npx jest -- integration/__tests__/minikube.tests.ts
    ```

**Expected behavior**
Lens should close automatically after all tests are executed successfully. Jest should automatically exit after Lens closes.

**Screenshots**
<img width="1442" alt="Screen Shot 2023-02-20 at 10 51 46 PM" src="https://user-images.githubusercontent.com/3536482/220511834-d0b12763-4b15-47b6-9927-c6ffb46e5f0e.png">

**Environment (please complete the following information):**
- Lens Version: a0fb46c3e65f0fdbee200857e793da9926ed0f4d
- OS: macOS and Linux (GitHub Actions)
- Installation method (e.g. snap or AppImage in Linux): From source

**Logs:**
```
$ npx jest -- integration/__tests__/minikube.tests.ts
  console.log
    Page opened: file:///Volumes/Storage/Developer/lens/packages/open-lens/dist/mac/OpenLens.app/Contents/Resources/app.asar/static/splash.html

      at ElectronApplication.log (integration/helpers/utils.ts:27:15)

  console.log
    Page opened: https://lens.app:49556/

      at ElectronApplication.log (integration/helpers/utils.ts:27:15)

  console.log
    info:    ▪ ⚡ LensProxy connection OK +3s
    info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /Volumes/Storage/Developer/lens/packages/open-lens/dist/mac/OpenLens.app/Contents/Resources/app.asar/static/splash.html... +2s
    info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +4s
    info:    ▪ [LENS-EXTENSIONS]: LOADING ... +31ms
    info:    ▪ [LENS-EXTENSIONS]: LOADED from /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-extensions.json +28ms
    info:    ▪ [LENS-WEBLINK-STORE]: LOADING ... +110ms
    info:    ▪ Running 5.1.4 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-weblink-store.json +5ms
    info:    ▪ Running 6.4.0-beta.13 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-weblink-store.json +24ms
    info:    ▪ [LENS-WEBLINK-STORE]: LOADED from /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-weblink-store.json +50ms
    info:    ▪ 📟 Setting protocol client for lens:// +44ms
    info:    ▪ 📟 Protocol client register succeeded ✅ +2ms
    info:    ▪ 🧩 Initializing extensions +2ms
    info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADING ... +108ms
    info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADED from /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-filesystem-provisioner-store.json +12ms
    info:    ▪ 🐚 Syncing shell environment +0ms
    info:    ┏ [UNIX-SHELL-ENV]: running against /usr/local/bin/zsh +2ms
    info:    ┃ [1] {
    info:    ┃ [2]   command: ` '/Volumes/Storage/Developer/lens/packages/open-lens/dist/mac/OpenLens.app/Contents/MacOS/OpenLens' -p '"909df85d2f1944cf9cec96461a0b2ce7" + JSON.stringify(process.env) + "909df85d2f1944cf9cec96461a0b2ce7"'`,
    info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
    info:    ┗ [4] }
    info:    ▪ [EXTENSIONS-LOADER]: auto initializing extensions +121ms
    info:    ▪ [LENS-HOTBAR-STORE]: LOADING ... +3ms
    info:    ▪ Running 5.0.0-alpha.0 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-hotbar-store.json +1ms
    info:    ▪ Running 5.0.0-alpha.2 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-hotbar-store.json +41ms
    info:    ▪ Running 5.0.0-beta.10 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-hotbar-store.json +32ms
    info:    ▪ Running 5.0.0-beta.5 migration for /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-hotbar-store.json +27ms
    info:    ▪ [LENS-HOTBAR-STORE]: LOADED from /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens/lens-hotbar-store.json +50ms
    info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /var/folders/mc/b5bnhqzj05b67zv7chskx2zw0000gp/T/lens-integration-testing/6e104cfa-fac1-48a4-93e3-847b1910f2cd/OpenLens +18ms
    info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /Users/caleb/.k8slens/extensions +501ms
    info:    ▪ [SHELL-SYNC]: Synced shell env +3s
    info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:49556... +38ms

      at ElectronApplication.log (integration/helpers/utils.ts:31:17)

 PASS  integration/__tests__/minikube.tests.ts (70.858 s)
  minikube tests
    ✓ noops (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        77.356 s
Ran all test suites matching /integration\/__tests__\/minikube.tests.ts/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Kubeconfig:**
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://127.0.0.1:6443
  name: default
- cluster:
    certificate-authority: /Users/caleb/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://localhost:56111
  name: minikube
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: redacted
    client-key-data: redacted
- name: minikube
  user:
    client-certificate: /Users/caleb/.minikube/profiles/minikube/client.crt
    client-key: /Users/caleb/.minikube/profiles/minikube/client.key
```

**Additional context**
None

**Comment by Nokel81** [comment]
Can you try with current master?

**Comment by alebcay** [comment]
I'm still seeing the same issue when building from b2160ae06c6d8e813a870c1badd7f1ea4c5ed24b. The resulting version coming out of my build from current master is still `6.4.0-beta.13` (even in ephemeral CI environments), I assume this is from the version just not being incremented anymore on master branch.

**Comment by Nokel81** [comment]
Ah yes, it is no longer being incremented. `master` is currently targeting `6.5.0`. This should be resolved soon and the version on `master` updated soon.

Don't know why we are not seeing this error case on the CI for this repo though.

**Comment by alebcay** [comment]
Looks like the `test:integration` script in package `open-lens` adds the `--forceExit` flag on Jest, so this hang/crash is ignored: https://github.com/lensapp/lens/blob/d29615c089aeb93a130db67fc5d7adc95c4105a6/packages/open-lens/package.json#L36

Adding this flag is sufficient for bypassing this issue downstream, but perhaps the underlying crash is still worth investigating.

**Comment by Nokel81** [comment]
Yes it probably is. Thanks for reporting it.
